services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "8080:80"
      - "5353:53/udp"
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    networks:
      adguard_vpn_net:
        ipv4_address: 172.31.0.2

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - SERVERURL=yourdomain.com
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=172.31.0.2
    volumes:
      - ./wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      adguard_vpn_net:
        ipv4_address: 172.31.0.3

networks:
  adguard_vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24